version: "3.1"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80

  db:
    image: postgres
    restart: always
    container_name: 3r_db
    environment:
      POSTGRES_PASSWORD: root_pass
      POSTGRES_USER: postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
      - /var/lib/3rstore/db-data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

  service:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: /3RStore/_3RStore/__init__.py
      LOCAL_EXEC: "true"
      FLASK_DEBUG: "true"
    volumes:
      - .:/3RStore/
    ports:
      - 8081:8081
